# ruff: noqa: SLF001
import hashlib
from functools import cache

from django.conf import settings
from django.contrib.postgres.indexes import HashIndex
from django.db import connection, models
from django.db.models import Model
from django.db.models.fields import Field
from django.db.utils import DEFAULT_DB_ALIAS
from django.utils.module_loading import import_string

from django_dbml.core.options import GenerationOptions
from django_dbml.core.schema import EnumValue, FieldDefinition, IndexDefinition, ProjectDefinition, RelationDefinition, TableDefinition
from django_dbml.core.selection import IGNORE_RELATION_TYPES, get_model_group, select_models
from django_dbml.utils import choices_to_markdown_table, to_snake_case


class SchemaBuilder:
    def __init__(self, options: GenerationOptions) -> None:
        self.options = options
        self.routers = [import_string(router)() for router in getattr(settings, "DATABASE_ROUTERS", [])]

    def build(self, app_labels: tuple[str, ...]) -> ProjectDefinition:
        project = ProjectDefinition(
            name=self.options.project_name,
            notes=self.options.project_notes,
            database_type=self.get_db_type(),
            include_timestamp=not self.options.disable_update_timestamp,
        )

        for model in select_models(app_labels):
            self._build_table(project, model)

        return project

    def _build_table(self, project: ProjectDefinition, model: type[Model]) -> None:
        group_name = get_model_group(model)
        table_name = self.get_table_name(model)
        table = TableDefinition(
            name=table_name,
            group=group_name,
            color=self.get_table_color(group_name),
        )
        project.tables[table_name] = table

        for field in model._meta.get_fields():
            if isinstance(field, IGNORE_RELATION_TYPES):
                continue

            if isinstance(field, models.fields.related.OneToOneField):
                field_name = f"{field.name}_id"
                table.relations.append(
                    RelationDefinition(
                        kind="one_to_one",
                        table_from=self.get_table_name(field.related_model),
                        table_from_field=field.target_field.name,
                        table_to=table_name,
                        table_to_field=field_name,
                    )
                )
                continue

            if isinstance(field, models.fields.related.ForeignKey):
                field_name = f"{field.name}_id"
                table.relations.append(
                    RelationDefinition(
                        kind="one_to_many",
                        table_from=self.get_table_name(field.related_model),
                        table_from_field=field.target_field.name,
                        table_to=table_name,
                        table_to_field=field_name,
                    )
                )
                continue

            if isinstance(field, models.fields.related.ManyToManyField):
                self._build_many_to_many_table(project, field, group_name)
                continue

            column_name = field.name
            table.fields[column_name] = self.build_field_definition(project, table_name, field)
            self.add_field_index(table, model, field, column_name)

        self.add_meta_indexes(table, model)
        self.add_table_notes(table, model)

    def _build_many_to_many_table(self, project: ProjectDefinition, field: Field, group_name: str) -> None:
        through_model = field.remote_field.through
        if "_" not in through_model._meta.model_name:
            return

        original_table_name = field.m2m_db_table()
        table_name = original_table_name.replace("_", ".", 1) if "_" in original_table_name else original_table_name
        if table_name in project.tables:
            return

        table = TableDefinition(
            name=table_name,
            group=group_name,
            color=self.get_table_color(group_name),
            note="This is a Many-To-Many linking table autogenerated by Django.",
        )
        if not self.options.table_names:
            table.note += f"\n\n*DB table: {original_table_name}*"

        table.relations.extend(
            [
                RelationDefinition(
                    kind="one_to_many",
                    table_from=table_name,
                    table_from_field=field.m2m_column_name(),
                    table_to=self.get_table_name(field.model),
                    table_to_field=field.m2m_target_field_name(),
                ),
                RelationDefinition(
                    kind="one_to_many",
                    table_from=table_name,
                    table_from_field=field.m2m_reverse_name(),
                    table_to=self.get_table_name(field.related_model),
                    table_to_field=field.m2m_reverse_target_field_name(),
                ),
            ]
        )
        table.fields["id"] = FieldDefinition(type="auto", pk=True)
        table.fields[field.m2m_reverse_name()] = FieldDefinition(type="auto")
        table.fields[field.m2m_column_name()] = FieldDefinition(type="auto")

        for field_name in [field.m2m_reverse_name(), field.m2m_column_name()]:
            table.indexes.append(
                IndexDefinition(
                    fields=[field_name],
                    type="btree",
                    name=connection.schema_editor()._create_index_name(original_table_name, [field_name]),
                )
            )
        table.indexes.append(
            IndexDefinition(
                fields=["id"],
                type="btree",
                name=f"{original_table_name}_pkey",
                unique=True,
                pk=True,
            )
        )
        table.indexes.append(
            IndexDefinition(
                fields=[field.m2m_column_name(), field.m2m_reverse_name()],
                type="btree",
                name=connection.schema_editor()._unique_constraint_name(
                    original_table_name,
                    [field.m2m_column_name(), field.m2m_reverse_name()],
                    quote=False,
                ),
                unique=True,
            )
        )

        project.tables[table_name] = table

    def build_field_definition(self, project: ProjectDefinition, table_name: str, field: Field) -> FieldDefinition:
        field_definition = FieldDefinition(type=map_field_type_to_dbml_type(type(field)))

        if getattr(field, "db_comment", ""):
            field_definition.note += field.db_comment.replace('"', '\\"')

        if getattr(field, "verbose_name", ""):
            verbose_name = field.verbose_name.replace('"', '\\"')
            field_definition.note += f"\n*{verbose_name}*"

        if getattr(field, "help_text", ""):
            help_text = field.help_text.replace('"', '\\"')
            field_definition.note += f"\n{help_text}"

        if getattr(field, "null", False):
            field_definition.null = True

        if getattr(field, "primary_key", False):
            field_definition.pk = True

        if getattr(field, "unique", False):
            field_definition.unique = True

        if getattr(field, "default", models.fields.NOT_PROVIDED) != models.fields.NOT_PROVIDED:
            field_definition.default = field.default

        if getattr(field, "choices", None):
            enum_name = self.get_enum_name(table_name, field.name, field_definition.type)
            field_definition.type = enum_name
            project.enums[enum_name] = [EnumValue(value=value, display=display) for value, display in field.choices]

        if getattr(field, "base_field", None) and field.base_field.choices:
            base_field_type = map_field_type_to_dbml_type(type(field.base_field))
            field_definition.note += f"\n\nBase field choices ({base_field_type}):"
            field_definition.note += f"\n{choices_to_markdown_table(field.base_field.choices)}"

        field_definition.note = field_definition.note.strip("\n")
        return field_definition

    def add_field_index(self, table: TableDefinition, model: type[Model], field: Field, field_name: str) -> None:
        if not (getattr(field, "db_index", False) or getattr(field, "primary_key", False) or getattr(field, "unique", False)):
            return

        if field.primary_key:
            index_name = f"{model._meta.db_table}_pkey"
        elif isinstance(field, models.fields.related.OneToOneField) or field.unique:
            index_name = f"{model._meta.db_table}_{field_name}_key"
        else:
            index_name = connection.schema_editor()._create_index_name(model._meta.db_table, [field_name])

        table.indexes.append(
            IndexDefinition(
                fields=[field_name],
                type="btree",
                name=index_name,
                unique=field.unique,
                pk=field.primary_key,
            )
        )

    def add_meta_indexes(self, table: TableDefinition, model: type[Model]) -> None:
        for index in model._meta.indexes:
            column_names = [model._meta._forward_fields_map[field_name].column for field_name in index.fields]
            table.indexes.append(
                IndexDefinition(
                    fields=column_names,
                    type="hash" if isinstance(index, HashIndex) else "btree",
                    name=index.name,
                )
            )

        for unique_together in model._meta.unique_together:
            column_names = [model._meta._forward_fields_map[field_name].column for field_name in unique_together]
            table.indexes.append(
                IndexDefinition(
                    fields=column_names,
                    type="btree",
                    name=connection.schema_editor()._unique_constraint_name(model._meta.db_table, column_names, quote=False),
                    unique=True,
                )
            )

    def add_table_notes(self, table: TableDefinition, model: type[Model]) -> None:
        if model.__doc__:
            table.note += f"\n{model.__doc__}"

        if getattr(model._meta, "db_table_comment", ""):
            comment = model._meta.db_table_comment.replace('"', '\\"')
            table.note += f"\n\n*DB comment: {comment}*"

        if not self.options.table_names:
            db_table = model._meta.db_table.replace('"', "").replace("'", "")
            if "." not in db_table:
                db_table = f"public.{db_table}"

            db_for_read = self.get_db_for_read(model)
            note = f"{table.note}\n\n*"
            if db_for_read is not None:
                note += f"DB: {db_for_read}, "
            note += f"table: {db_table}*"
            table.note = note

    def get_table_name(self, model: type[Model]) -> str:
        if self.options.table_names:
            return model._meta.db_table
        return model._meta.label

    def get_table_color(self, group_name: str) -> str:
        if not self.options.color_by_app:
            return ""
        return f"#{hashlib.sha256(group_name.encode()).hexdigest()[:6]}"

    def get_db_type(self) -> str:
        db = settings.DATABASES["default"]
        engine = db["ENGINE"].lower()

        if "postgres" in engine:
            return "PostgreSQL"
        if "sqlite" in engine:
            return "SQLite"
        if "mysql" in engine:
            return "MySQL"
        if "oracle" in engine:
            return "Oracle"
        if "mssql" in engine:
            return "Microsoft SQL"

        return f"Unknown ({db['ENGINE']})"

    def get_db_for_read(self, model: type[Model]) -> str | None:
        for router in self.routers:
            if hasattr(router, "db_for_read"):
                db_for_read = router.db_for_read(model) or DEFAULT_DB_ALIAS
                if db_for_read:
                    return db_for_read
        return None

    def get_enum_name(self, table_name: str, field_name: str, field_type: str) -> str:
        if "." in table_name:
            schema_name, model_name = table_name.split(".", 1)
        elif "_" in table_name:
            schema_name, model_name = table_name.split("_", 1)
        else:
            schema_name, model_name = "public", table_name

        return f"{schema_name}.{field_type}_{model_name}_{field_name}".lower()


@cache
def map_field_type_to_dbml_type(field: type[Field]) -> str:
    """Given a field class, return the DBML type used in the schema."""

    return to_snake_case(field.__name__.removesuffix("Field"))
