Table Follow {
  id auto [pk, unique]
Table Follow {
  id auto [pk, unique]
  following_user foreign_key 
  followed_user foreign_key 
  created_at date_time 
  Note: '''The user follow model.'''
}

ref: Follow.following_user > User.id
ref: Follow.followed_user > User.id
Table Post {
  id auto [pk, unique]
  title char 
  body text [note:"Content of the post"]
  user foreign_key 
  status char [default:`"draft"`]
  created_at date_time 
  Note: '''The post model.'''
}

ref: Post.user > User.id
